apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-data
  namespace: dev-env
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-server-data
  namespace: dev-env
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
