apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vscode
  name: vscode
  namespace: dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode
  template:
    metadata:
      labels:
        app: vscode
    spec:
      containers:
        - image: vscode:latest
          name: vscode
          volumeMounts:
            - name: docker-context
              mountPath: /home/user/.docker
            - name: docker-client-cert
              mountPath: /home/user/.docker/cert
            - name: home-dir
              mountPath: /home/user/
            - name: kube-config
              mountPath: /home/user/.kube
            - name: helm-data
              mountPath: /home/user/.config/helm
            - name: vscode-data
              mountPath: /home/user/.vscode
            - name: vscode-server-data
              mountPath: /home/user/.vscode-server
      volumes:
        - name: docker-context
          persistentVolumeClaim:
            claimName: docker-context
        - name: docker-client-cert
          secret:
            secretName: docker-client-cert
            defaultMode: 0444
            items:
              - key: ca.pem
                path: ca.pem
              - key: key.pem
                path: key.pem
              - key: cert.pem
                path: cert.pem
        - name: home-dir
          persistentVolumeClaim:
            claimName: home-dir
        - name: kube-config
          secret:
            secretName: kube-config
            items:
              - key: config
                path: config
        - name: helm-data
          persistentVolumeClaim:
            claimName: helm-data
        - name: vscode-data
          persistentVolumeClaim:
            claimName: vscode-data
        - name: vscode-server-data
          persistentVolumeClaim:
            claimName: vscode-server-data
      imagePullSecrets:
        - name: my-registry
---
apiVersion: v1
kind: Service
metadata:
  name: vscode
  namespace: dev-env
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: vscode
  type: ClusterIP
