apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-dir
  namespace: dev-env
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-data
  namespace: dev-env
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-context
  namespace: dev-env
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
