apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
          name: oauth2-proxy
          envFrom:
            - configMapRef:
                name: oauth2-proxy
            - secretRef:
                name: oauth2-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: dev-env
spec:
  ports:
    - name: oauth2-proxy
      port: 80
      targetPort: 4180
  selector:
    app: oauth2-proxy
  type: LoadBalancer
