apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: dev-env
data:
  OAUTH2_PROXY_CLIENT_ID: dnNjb2RlCg== # VSCode
  OAUTH2_PROXY_CLIENT_SECRET: YWcybXZjQVd6aDBjRWVBWjhNN2NaYWVkaFdiZlZzeE4K # ag2mvcAWzh0cEeAZ8M7cZaedhWbfVsxN # From Keycloak Client Credentials
  OAUTH2_PROXY_COOKIE_SECRET: YTFaOXpSTnpWaFBZeGliZVN1N1pyT3NfT1dlUzJfMVk2NWQ5QlhzWXFpdz0K # openssl rand -base64 32 | tr -- '+/' '-_' | base64
