apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy
  namespace: dev-env
data:
  OAUTH2_PROXY_PROVIDER: oidc
  OAUTH2_PROXY_REDIRECT_URL: http://Oauth2-Proxy_IP:4180/oauth2/callback
  OAUTH2_PROXY_OIDC_ISSUER_URL: http://Keycloak_IP:8080/realms/default
  OAUTH2_PROXY_COOKIE_SECURE: "false"
  OAUTH2_PROXY_COOKIE_NAME: "oauth2_proxy"
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
  OAUTH2_PROXY_UPSTREAMS: http://vscode:8000/
  OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_SCOPE: openid email profile
  OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
  OAUTH2_PROXY_PASS_USER_HEADERS: "true"
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
  OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
