apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dind
  name: dind
  namespace: dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
        - image: dind:latest
          name: dind
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run
            - name: home-dir
              mountPath: ~/
            - name: docker-data
              mountPath: /var/lib/docker
      volumes:
        - name: docker-socket
          persistentVolumeClaim:
            claimName: docker-socket
        - name: home-dir
          persistentVolumeClaim:
            claimName: home-dir
        - name: docker-data
          persistentVolumeClaim:
            claimName: docker-data
      imagePullSecrets:
        - name: my-registry
