apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-socket
  namespace: dev-env
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-data
  namespace: dev-env
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
